### ISSUE TITLE
Levelshifter on preview but not in gerber-files

### ISSUE THREAD

**Issue by lebowski42** [klein0r/pcb-ws2812-ethernet-controller#2]
Hi,
the preview shows pads for an level shifter (SN74AHCT125DR). Opening the KiCad-Files i also can see this component. But this component is missing in the previesReal.png and the prebuild gerber-files (gerber.zip). 
Can you tell me, what is the right version (with SN74AHCT125DR or without)?

Thank you.

**Comment by klein0r** [comment]
Yes, I've designed a new version with level shifter but I haven't tested it right now.
So there is no release until I know that it is working.

**Comment by lebowski42** [comment]
Ok, thank you. 
I'll give the new version a try and will post it here.

**Comment by lebowski42** [comment]
And just another question: Why do you use an 330Ohm resistor for the data output and not 62 Ohm as suggested in the wled doc: https://kno.wled.ge/basics/getting-started/

**Comment by klein0r** [comment]
You find hundreds of different recommendations for that resistor.

Adafruit: https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices

> Place a 300 to 500 Ohm resistor between the Arduino data output pin and the input to the first NeoPixel.

or https://forum.arduino.cc/t/new-to-sk6812-rgbw-led-strip-am-i-doing-this-right/562072

Feel free to use 62Ohm 😄
